### ISSUE TITLE
Do not run callbacks inside a goroutine

### ISSUE THREAD

**Issue by belak** [thoj/go-ircevent#51]
This is somewhat of an important discussion to have. I opened it because of PR #50 (and my own experiences in the past).

Currently all callbacks are run inside a goroutine. This leads to unpredictable behavior, especially when attempting to do stuff which is order important (such as authenticating users).

I personally think that all callbacks should not be run in a goroutine, as it breaks the idea of order in IRC. Users should be able to run portions of their callbacks in a goroutine, but it should not be required.

**Comment by fluffle** [comment]
$0.02 since I had similar problems in goirc: I ended up having a "HandleBG" function that allowed people to add callbacks that had no requirements for IRC protocol consistency. Blocking the event loop is bad, but maintaining protocol consistency requires that all handlers for a particular incoming line are run before any of the handlers for subsequent lines.

**Comment by darkliquid** [comment]
Rather than running each callback in it's own goroutine, you could add each callback call to a worker queue and have a single goroutine sat in the background working through them in order. That keeps callbacks outside of the main thread, while still keeping them in order. The main issue to deal with then is avoiding queue-exhaustion.

**Comment by belak** [comment]
Why even bother requiring the user to specify? The handlers themselves are the same... and if they need something to run in the background, they can use `go func()` themselves.

**Comment by hashworks** [comment]
I'm with @belak. What is the status here?

**Comment by thoj** [comment]
@belak @hashworks 
See da78ed515c0f0833e7a92c7cc52898176198e2c1

Decided to just break everyone's code to fix this. Only small changes was needed in my bots but this is a quite mayor change that will break a lot of code. Please test.

**Comment by lidel** [comment]
I think this can be closed: no issues so far.

My old code worked without any change,
and adding a goroutine to one of callbacks was just a 2-line change.

**Comment by thoj** [comment]
Ok thank you! :)
